app/api/api_v1/api.py
app/api/api_v1/endpoints/bodies.py
app/api/api_v1/params/bodies.py
app/api/deps.py
app/tests/api/api_v1/test_bodies.py
app/tests/conftest.py

feat: Added /api/v1/bodies endpoint to the API. 
Includes associated test suite for module export definition and expected output, for different API scenarios and queries.

feat: Added /api/v1/bodies endpoint to the API.

---

app/models/body.py

feat: Added altitude @hybrid_method.expression to Body. 
“hybrid” means the attribute has distinct behaviours defined at the class level and at the instance level, allowing the usage of database level queries for Body attributes that are dynamically defined.
This PR is preparation work for providing a solution to: #28

feat: Added altitude @hybrid_method.expression to Body.

---

app/core/config.py
app/main.py
app/tests/api/api_v1/test_headers.py

feat: Added CustomXHeadersMiddleware(). 
Includes associated test suite for headers definition and expected output.

feat: Added CustomXHeadersMiddleware().

---

app/api/api_v1/params/bodies.py
app/tests/api/api_v1/test_bodies.py

feat: Added the ability to specify altitude search params in /api/bodies endpoints. 
Includes associated test for a specific date in time to ensure we are getting a known and valid result.
Closes #28

feat: Added altitude search params specification.

---

app/schemas/body.py

feat: Updated BodyBase with pydantic Field schema.

feat: Updated BodyBase with pydantic Field schema.

---

app/seed/stars.py

feat: Ensured star types match SIMBAD Astronomical Database types by default.

feat: Ensured star types match SIMBAD Astronomical Database types by default.

---

app/main.py
app/tests/api/api_v1/test_bodies.py
app/tests/api/api_v1/test_headers.py

feat: Added TrustedHostMiddleware(). 
Includes associated test suite for headers definition and expected output.

feat: Added TrustedHostMiddleware().

---

app/main.py
app/tests/api/api_v1/test_bodies.py
app/tests/api/api_v1/test_headers.py
poetry.lock
pyproject.toml

feat: Updated test suite to use async with httpx.AsyncClient() calls. 
Includes utilising @pytest.mark.anyio decorator. 
Includes associated changes to testing setup, but not the underlying tests.

feat: Updated test suite to use async with httpx.AsyncClient().

---

app/api/api_v1/endpoints/bodies.py
app/main.py
app/tests/api/api_v1/test_bodies.py
app/tests/api/api_v1/test_headers.py
app/tests/conftest.py
local.yml
poetry.lock
pyproject.toml
pytest.ini

feat: Added aioredis and FastAPICache.init() to app. 
Added 1 year expiry to the cache for bodies:list and bodies:list-paginated. 
Includes amending @pytest.fixture(scope="module") client generator and @pytest.fixture(scope="session") event_loop generator. 
Includes updates to the pytest.ini file for asyncio mode.

feat: Added aioredis and FastAPICache.init() to app.

---

app/api/api_v1/params/bodies.py
app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Refined the name lookup to include Body { iau } field. 
Includes associated test suite for headers definition and expected output.

feat: Refined the name lookup to include Body { iau } field.

---

app/api/api_v1/params/bodies.py

feat: Added { start, end } Optional fields to BodyQueryParams

feat: Added { start, end } Optional fields to BodyQueryParams

---

app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Added the ability to filter bodies on { start, end } on dynamic altitude. 
Includes associated additions to test suite.

feat: Added the ability to filter bodies on { start, end } on dynamic altitude.

---

app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Added query.order_by() apparent magnitude { body.m } field. 
Includes associated changes to expected test output for improved ordering.

feat: Added query.order_by() apparent magnitude { body.m } field.

---

app/db/session.py

feat: Added settings.PROJECT_ENVIRONMENT flag to create_engine() call.

feat: Added settings.PROJECT_ENVIRONMENT flag to create_engine() call.

---

poetry.lock
pyproject.toml

chore: Bumped uvicorn version => 0.18.2 in pyproject.toml.

chore: Bumped uvicorn version => 0.18.2 in pyproject.toml.

---

app/main.py

feat: Added HTTP 302 Found status code to the base RedirectResponse.

feat: Added HTTP 302 Found status code to the base RedirectResponse.

---

app/main.py

feat: Added redirect_slashes to equal true in main.py.

feat: Added redirect_slashes to equal true in main.py.

---

alembic/env.py

refactor: Added port parameter to alembic/env.py:get_url() call.

refactor: Added port parameter to alembic/env.py:get_url() call.

---

poetry.lock
pyproject.toml

chore: Upgraded base framework to poetry add fastapi@0.81.0 and starlette => "0.19.1".

chore: Upgraded base framework to poetry add fastapi@0.81.0 and starlette => "0.19.1".

---

alembic/versions/d246e2f4a338_feat_added_body_model_e_g_star_galaxy_.py
app/models/body.py

feat: Updated Body model (e.g., Star, Galaxy, Nebulae etc.)

feat: Updated Body model (e.g., Star, Galaxy, Nebulae etc.)

---

app/init_db_seed.py

refactor: Amended to accept db Session type in seed functions.

refactor: Amended to accept db Session type in seed functions.

---

app/crud/crud_body.py

feat: Added delete_multi to CRUDBody() model.

feat: Added delete_multi to CRUDBody() model.

---

app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Added ability to query { name } column of Body with a sub-string. 
Includes associated additions to test suite for module export definition and expected output.

feat: Added ability to query { name } column of Body with a sub-string.

---

app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Added ability to query { constellation } column of Body with a sub-string. 
Includes associated additions to test suite for module export definition and expected output.

feat: Added ability to query { constellation } column of Body with a sub-string.

---

app/api/api_v1/params/bodies.py
app/crud/crud_body.py
app/tests/api/api_v1/test_bodies.py

feat: Added ability to query { type } column of Body with a sub-string. 
Includes associated additions to test suite for module export definition and expected output.

feat: Added ability to query { type } column of Body with a sub-string.

---

alembic/versions/6c37d2f9f30b_feat_added_body_model_e_g_star_galaxy_.py
app/models/body.py
app/schemas/body.py

feat: Added { ..., b } (semi-major axis) field to Body model. 
Includes associated updates to BodyBase and BodyCreate schema. 
Includes updating alembic migrations for "feat: Added Body model (e.g., Star, Galaxy, Nebulae etc.)".

feat: Added { ..., b } (semi-major axis) field to Body model.

---

alembic/versions/f3b35e23e6d7_feat_added_body_model_e_g_star_galaxy_.py
app/models/body.py
app/schemas/body.py

feat: Added { ..., z } (redshift) field to Body model. 
Includes associated updates to BodyBase and BodyCreate schema. 
Includes updating alembic migrations for "feat: Added Body model (e.g., Star, Galaxy, Nebulae etc.)".

feat: Added { ..., z } (redshift) field to Body model.

---

alembic/versions/60bc843ba6b5_feat_added_body_model_e_g_star_galaxy_.py
app/models/body.py
app/schemas/body.py

feat: Added { ..., μra, μdec } (proper motion) fields to Body model. 
Includes associated updates to BodyBase and BodyCreate schema. 
Includes updating alembic migrations for "feat: Added Body model (e.g., Star, Galaxy, Nebulae etc.)".

feat: Added { ..., μra, μdec } (proper motion) fields to Body model.

---

app/crud/crud_body.py

feat: Added CRUDBody.merge_or_create() base method to crud_body.

feat: Added CRUDBody.merge_or_create() base method to crud_body.

---

app/core/config.py

feat: Amended BACKEND_CORS_ORIGINS in config.py BaseSettings.

feat: Amended BACKEND_CORS_ORIGINS in config.py BaseSettings.

---

app/core/config.py
app/main.py

feat: Amended aioredis @app.on_event("startup") to fail quietly if FastAPICache cannot initialise.

feat: Amended aioredis @app.on_event("startup") to fail quietly if FastAPICache cannot initialise.

---

Dockerfile
docker-compose.yml
start.sh

chore: Added start.sh entrypoint for base docker-compose.yml.

chore: Added start.sh entrypoint for base docker-compose.yml.

---

poetry.lock
pyproject.toml

feat: Added cloud-sql-python-connector => v1.1.0 dependency to pyproject.toml

feat: Added cloud-sql-python-connector => v1.1.0 dependency to pyproject.toml

---

app/main.py

feat: Updated ALLOWED_HOSTS to wildcard *

feat: Updated ALLOWED_HOSTS to wildcard *

---

app/api/api_v1/endpoints/bodies.py
app/core/config.py
app/main.py

feat: Amended aioredis @app.on_event("startup") to only initialise FastAPICache if specified.

feat: Amended aioredis @app.on_event("startup") to only initialise FastAPICache if specified.

---

app/main.py

feat: Added add_helmet_headers(request: Request, call_next) @app.middleware for Helmet style security headers.

feat: Added add_helmet_headers(request: Request, call_next) @app.middleware.
